spring.application.name=JeyahShopAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/jeyah
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database=postgresql

spring.security.oauth2.resourceserver.jwt.issuer-uri= http://localhost:9090/realms/JeyahShop
spring.security.oauth2.resourceserver.jwt.jwk-set-uri= http://localhost:9090/realms/JeyahShop/protocol/openid-connect/certs

jwt.auth.converter.resource-id: jeyah-shop-rest-api
jwt.auth.converter.principle-attribute: preferred_username